name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: ros-cuda

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda_version: ["11.0", "11.1"]
        ros_distro: ["noetic", "melodic", "kinetic"]

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./BUILD-DOCKER-IMAGE.sh $IMAGE_NAME ${{matrix.cuda_version}} ${{matrix.ros_distro}}

  # Push image to GitHub Packages.
  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        cuda_version: ["11.0", "11.1"]
        ros_distro: ["noetic", "melodic", "kinetic"]

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: ./BUILD-DOCKER-IMAGE.sh $IMAGE_NAME ${{matrix.cuda_version}} ${{matrix.ros_distro}}

      - name: Log into GitHub Container Registry
        run: echo "${{secrets.CR_PAT}}" | docker login https://ghcr.io -u ${{github.actor}} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{github.repository_owner}}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Set VERSION
          VERSION=${{matrix.cuda_version}}-runtime-${{matrix.ros_distro}}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION